baseurl = "https://xshyamx.github.io"
languageCode = "en"
title = "Shyam's Blog"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/xshyamx\">Shyam</a>"
# Number of posts per page
Paginate = 5
enableRobotsTXT = true

publishDir = "docs"

[params.features]

[params.assets]
customCSS = ["css/custom.css"]

[params.rss]
includeContent = true # Includes whole content in rss
authorName = "shyam" # Site author's full name

[params.info]
homeTitle = "Shyam's Blog" # Title for home page
poweredby = true # Adds powered by Hugo and Kiss below Copyright section
related = true # Includes related articles

[params.social]

github = "xshyamx"
gitlab = "xshyamx"

[params.social.config]
platforms = ["github","gitlab"]


[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true


